#define VIAL_KEYBOARD_UID {0xD6, 0x1C, 0xF2, 0xF2, 0x7F, 0x55, 0x4D, 0xF3}
#define VIAL_UNLOCK_COMBO_ROWS { 1, 1 }
#define VIAL_UNLOCK_COMBO_COLS { 1, 2 }

#define RGB_MATRIX_FRAMEBUFFER_EFFECTS
#define RGB_MATRIX_KEYPRESSES
